### PR TITLE
YAML

### PR DESCRIPTION
**Pull request by IsaiahPatton**
Add YAML configuration for plugins

### CODE REVIEW

**Comment by IsaiahPatton** [comment]
5 days later......

**Comment by CodeCrafter47** [comment]
Please seek a proper discussion before adding big features. See my comment on the forum.

And yes I know I've been lazy in replying to the configuration issue. I'm sorry about that.

**Comment by CodeCrafter47** [comment]
Ok, looking at the responses on the forum, yaml seems to be the preferred config format.

What is the advantage of creating the config API ourselves, lets say over pulling [these three files](https://github.com/SpigotMC/BungeeCord/tree/master/config/src/main/java/net/md_5/bungee/config) from BungeeCord? Don't get me wrong I do not question your ability to create something like this. But using an existing library will reduce the amount of work we have to do, also regarding maintenance of the config API.

**Comment by IsaiahPatton** [comment]
Then it would be net.md_5.bungee.config and won't show up on https://ci.codecrafter47.de/job/Rainbow/org.projectrainbow$PluginReference/javadoc/
(Bungee chat does not show up also)


It would need to be reconfigured to the package PluginReference to show on the javadoc

Maven shade plugin <configuration> in PluginReference/pom.xml:

<relocations>
  <relocation>
    <pattern>net.md_5.bungee.config</pattern>
    <shadedPattern>PluginReference.configuration</shadedPattern>
  </relocation>
</relocations>

http://pastebin.com/cz4qam2F

Relocating the classes would be helpfull as the JavaDocs would be on one page and users would not have to go find the Bungee javadocs.

**Comment by CodeCrafter47** [comment]
As already stated in my reply to #18 relocating library classes is bad. Also the relocation won't automatically make them show up in the javadoc. 515736584ebf063d9639ea6981ea1bfb2de2859e does. See [https://ci.codecrafter47.de/job/Rainbow/org.projectrainbow$PluginReference/javadoc/index.html?overview-summary.html](https://ci.codecrafter47.de/job/Rainbow/org.projectrainbow$PluginReference/javadoc/index.html?overview-summary.html), it now shows the chat javadoc.

Regarding the BungeeCord license, you only require written permission of the author when using it for commercial software hosting services.

**Comment by IsaiahPatton** [comment]
You said
> The libraries need to stay where they are as **plugins might use them**

No plugins use Bungee configuration (as its not added yet).

**Comment by CodeCrafter47** [comment]
Yeah, no plugin uses them as of now, but a plugin might decide to use a library which uses it, so still bad.

If a plugin decides to ship its own copy of the bungeecord configuration module then it would be the responsibility of the plugin to relocate its copy to avoid conflicts.

The way I see it the general rule is not to relocate any packages which are exposed to plugins as part of the API, because plugins might use other software components which expect the exposed libraries in their default package. While this might be unlikely to happen for the bungeecord config API, it definitely happens for other libraries which are available to rainbow plugins, mainly guava, gson and apache commons.

Regarding usability I think we can add some convenience methods to PluginBase to load and save the config, and also for loading the default config. When using these your IDE would automatically point you to the right class.

**Comment by IsaiahPatton** [comment]
Then pull the files.

**Comment by CodeCrafter47** [comment]
0f3bed7ee35ccb54029cf358a64e1199e1c279ab

I've added some convenience methods to PluginBase to load & save the config file. Do you think it is fine like that or am I missing something?

**Comment by IsaiahPatton** [comment]
Its good.

**Pull request closed without merging**
