### PR TITLE
Auto download BukkitBridge & fixes a crash bug I was having

### PR DESCRIPTION
**Pull request by IsaiahPatton**
Auto downloads RainbowBukkitBridge

Also renamed "Downloading minecraft server" message to "Downloading minecraft-server.jar"

https://github.com/CodeCrafter47/Rainbow/issues/2

### CODE REVIEW

**Comment by CodeCrafter47** [comment]
I got the changes to the start script: 11f28e0c872a559071d4d628659ed29bc563553a

Not sure whether I like auto-downloading the PluginBukkitBridge.jar. When the users download it themselves they can select the version they need (not everyone uses the latest minecraft version). Also some people might not need it at all. But I can also see how this would make it easier for users. So I'm not really sure on that point.

**Comment by IsaiahPatton** [comment]
Aslo the Bukkit Bridge does not work

In Jar: PluginBukkitBridge.MyPlugin

Console says it needs: RainbowBukkitBridge.MyPlugin

**Comment by CodeCrafter47** [comment]
That's an issue in your auto-download code. The file needs to be called PluginBukkitBridge.jar not RainbowBukkitBridge.jar.

**Comment by IsaiahPatton** [comment]
I've added a disable auto downloading the Bukkit Bridge

**Pull request closed without merging**
